### ISSUE TITLE
可以企业微信告警和互动信息吗

### ISSUE THREAD

**Issue by opcache** [lenye/pmsg#1]
互动信息，比如我发企业微信机器人信息 aaa，机器人通过程序判断恢复AAA什么的

**Comment by lenye** [comment]
`pmsg` 目前不支持发送企业微信群机器人消息。
下一步会开发这个功能

**Comment by lenye** [comment]
0.3.6版本开始，可以推送企业微信群机器人消息
https://github.com/lenye/pmsg/releases
