### ISSUE TITLE
Base64 encoder 未 Close 导致的企业微信机器人图片发送失败

### ISSUE THREAD

**Issue by 9lie** [lenye/pmsg#2]
企业微信机器人，使用 `ImageFile2Meta` 生成的结构体发送图片失败，错误信息
```
weixin request error; errcode: 301019, errmsg: "media md5 not match, more info at https://open.work.weixin.qq.com/devtool/query?e=301019"
```
测试图片：https://user-images.githubusercontent.com/26185872/211131620-4e31726f-4767-403e-b17a-263ebc7a25a1.png

实际原因是 baser64 encoder 没有 Close 导致最后几个字节没有被编码。

参考官方 example：https://github.com/golang/go/blob/master/src/encoding/base64/example_test.go#L77

修复建议：https://github.com/lenye/pmsg/blob/main/pkg/weixin/work/bot/meta.go#L75 增加调用 `Close()`

**Comment by lenye** [comment]
错误修复[v0.4.4](https://github.com/lenye/pmsg/releases/tag/v0.4.4)
